name: action to login on openshift cluster
description: action to login
inputs:
  image:
    description: image name
    required: true
  target:
    description: target name
    required: true
  
outputs:
  image:
    description: built image
    value: ${{ steps.build.outputs.image }}
runs:
  using: 'composite'
  steps:
    - name: Build docker image
      id: build
      shell: bash
      run: |
        docker build --target ${{ inputs.target }} -t ${{ inputs.image }} .
