name: push image to opemshift
description:
inputs:
 image:
  description:
  required: true


runs:
 using: 'composite'
 steps:
 - name: tag image
   env: 
    name: dev
    image: ${{ inputs.image }}
    
   runs: |
    docker push ${{ env.image }}
