name: push image to opemshift
description:
inputs:
 image:
  description: image built
  required: true
  

runs:
 using: 'composite'
 steps:
   - name: push to openshift image repository
     runs: |
      docker push ${{ env.image }}
