name: Java Build Workflow with Docker

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Choose node.js, python or Java'
        required: true
        type: choice
        default: Java
        options:
          - Java
          - python
          - node.js

  # push:
  #   branches:
  #     - main

jobs:
  Build:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    outputs:
     image_tag: ${{ steps.build.outputs.image }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup Java
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.app == 'Java' }}
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      - name: setup node js
        if: ${{ github.event.inputs.app == 'node.js' }}
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies,Test,Build (node)
        if: ${{ github.event.inputs.app == 'node.js' }}
        run: | 
         ## Install dependencies
         npm install
         ## Run tests
         npm test
         ## run build
         npm run build
         ls -lrt

      - name: Build with Maven
        id: build
        if: ${{ github.event.inputs.app == 'Java' }}
        run: mvn clean install -DskipTests

      - name: Build Docker image (node)
        id: build
        if: ${{ github.event.inputs.app == 'node.js' }}
        run: |
         docker build --target runtime-node -t demo-app-node:${{ github.sha }} .

      - name: Build Docker image (java)
        id: build
        if: ${{ github.event.inputs.app == 'Java' }}
        uses:
        with:
         target: runtime-java
         image: demo-app-java:${{ github.sha }}
         
      - name: upload an artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: staging
          retention: 1

      - name: download an artifact
        uses: actions/download-artifact@v4
        with:
         name: myapp
         path: staging

  Deploy:
   runs-on: ubuntu-latest
   needs: Build
   steps:
   # - name: move image to jfrog artifactory or any other docker hub
   #  with:
   #   username:
   #   password: 
     
   - name: Login to Openshift
     uses: actions/login-to-cluster
     with:
      username: ${{ secret.username }}
      password: ${{ secrets.password }}
      namespace: dev
      
   - name: Push image into some namespace
     uses: actions/push-to-openshift
     with:
      image: ${{ needs.Build.outputs.image_tag }}"
      
   - name: Deploy image in openshift cluser
     run: | 
      oc process -f generic.json \
      -p IMAGE_TAG="demo-app-java:${{ github.sha }}" \
      -p SERVICE_NAME="kdskd" \
      -p VAULT_USER="user" | oc apply -f -
     
    
  
   
      
     

